# Generated by Django 4.1.4 on 2023-01-12 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('seatNum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Showings',
            fields=[
                ('showingID', models.AutoField(primary_key=True, serialize=False)),
                ('showingTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('filmID', models.AutoField(primary_key=True, serialize=False)),
                ('filmName', models.CharField(max_length=50)),
                ('filmLength', models.TimeField()),
                ('showingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.showings')),
            ],
        ),
    ]
