# Generated by Django 4.1.4 on 2023-01-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_booking_showings_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='showingID',
        ),
    ]
