# Generated by Django 4.1.4 on 2023-01-15 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_remove_film_showingid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ageRating',
            fields=[
                ('ageID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ageRating', models.CharField(choices=[('U', 'U'), ('PG', 'PG'), ('12', '12'), ('12A', '12A'), ('15', '15'), ('18', '18')], default='000000', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='filmName',
            field=models.ForeignKey(default='000000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hello.film'),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticketType',
            field=models.CharField(choices=[('Student', 'Student'), ('Child', 'Child'), ('Adult', 'Adult')], default='Student', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='filmID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='showings',
            name='showingID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='ageRating',
            field=models.ForeignKey(default='000000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hello.agerating'),
        ),
    ]
